# Generated by Django 3.1.2 on 2021-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanrank',
            name='actor',
            field=models.TextField(verbose_name='主演'),
        ),
    ]
