# Generated by Django 3.1.2 on 2021-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210113_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanrank',
            name='srank',
            field=models.IntegerField(verbose_name='排名'),
        ),
    ]
