# Generated by Django 3.1.2 on 2021-01-12 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 16, 11, 17), verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='registercaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 16, 11, 17), verbose_name='过期时间'),
        ),
    ]
