# Generated by Django 3.1.2 on 2021-01-13 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_auto_20210113_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 15, 4, 38), verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='registercaptcha',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 15, 4, 38), verbose_name='过期时间'),
        ),
    ]
